### ISSUE TITLE
Update TGM Plugin activation

### ISSUE THREAD

**Issue by vpratfr** [marvinlabs/baobab#6]
Package tgm/plugin-activation is abandoned, you should avoid using it. Use tgmpa/tgm-plugin-activation instead.

**Comment by tlartaud** [comment]
Had also changed some others things because i had errors messages

in dependencies.php, change

```
// Merge user configuration with defaults
        $config = isset($data['options']) ? array_merge_recursive($defaults, $data['options']) : $defaults;

// TO


// Merge user configuration with defaults
        $config = isset($data['options']) ? array_merge($defaults, $data['options']) : $defaults;
```

And, in this file, also update the paths to tgm to look like this

```
require_once(Paths::vendors('tgmpa/tgm-plugin-activation/class-tgm-plugin-activation.php'));
Hooks::action('tgmpa_register', $this, 'configureTgmPluginActivationLibrary');
```

**Comment by vpratfr** [comment]
@tlartaud  du changement a faire ou c'est tout bon ?

**Comment by tlartaud** [comment]
@vpratfr ah yep, bien vu, il y'avait l'histoire du array_merge aussi. J'ai ajouté une nouvelle PR. Closing.
